import type { Metadata } from "next";
// import { Poppins } from 'next/font/google'
import "./globals.css";
import Script from 'next/script';


// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['400', '600'], // normal and bold
//   variable: '--font-poppins',
// })

export const metadata: Metadata = {
  title: "Harsh Singh Baghel",
  description: "Generated by create next app",
  icons: {
    icon: "/letter-h-copy.png", // or .ico
    shortcut: "/letter-h.png", // or .ico
    apple: "/letter-h.png", // or .ico
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={poppins.variable}
      >
        {/* Google Analytics - gtag (placed in layout so it's loaded once site-wide) */}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=G-G51SJM0P6M || 'G-G51SJM0P6M'}`}
          strategy="afterInteractive"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', '${process.env.NEXT_PUBLIC_GA_ID || 'G-G51SJM0P6M'}');`}
        </Script>
        {children}
      </body>
    </html>
  );
}
