import type { Metadata } from "next";
// import { Poppins } from 'next/font/google'
import "./globals.css";


// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['400', '600'], // normal and bold
//   variable: '--font-poppins',
// })

export const metadata: Metadata = {
  title: "Harsh Singh Baghel",
  description: "Generated by create next app",
  icons: {
    icon: "/letter-h-copy.png", // or .ico
    shortcut: "/letter-h.png", // or .ico
    apple: "/letter-h.png", // or .ico
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={poppins.variable}
      >
        {children}
      </body>
    </html>
  );
}
